version: '3.8'
services:
  db:
    image: mongo:jammy
    container_name: db_c
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=chat
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: on-failure
    networks:
      - network

  server:
    build: ./server
    container_name: server_c
    environment:
      - DB_CONNECTION=mongodb://user:password@db:27017
      - SERVER_PORT=4000
      - SECRET_KEY=*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeSh
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge